[window_mode]
width = 960.0
height = 600.0
maximized = false
fullscreen_type = "Windowed"
borderless = false
min_width = 0.0
min_height = 0.0
max_width = 0.0
max_height = 0.0
hidpi = false
resizable = true

[window_setup]
title = "Open Moonstone"
samples = "Zero"
vsync = true
transparent = false
icon = ""
srgb = true

[backend]
type = "OpenGL"
major = 3
minor = 2

[modules]
gamepad = true
audio = true
