[package]
edition = '2018'
name = "openmoonstone"
version = "0.1.0"
authors = ["Joe Tsoi <joetsoi@users.noreply.github.com>"]

[dependencies]
byteorder = "*"
bv = "*"
#ggez-goodies = { git = "https://github.com/joetsoi/ggez-goodies.git"}
ggez-goodies = { git = "https://github.com/joetsoi/ggez-goodies.git", branch = "push-multiple"}
failure = "*"
failure_derive = "*"
#image = "*"
pest = "*"
pest_derive = "*"
rect_packer = "*"
specs = "0.14.1"
specs-derive = "0.2.0"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
warmy = "0.8.0"
maplit = "*"
lazy_static = "1.2.0"

[dependencies.ggez]
version = "*"
features = ["cargo-resource-root"]

[dependencies.shred]
version = "*"
features = ["nightly"]

[dev-dependencies]
rustfmt-nightly = "*"
