cargo-features = ["edition"]

[package]
edition = '2018'
name = "openmoonstone"
version = "0.1.0"
authors = ["Joe Tsoi <joetsoi@users.noreply.github.com>"]

[dependencies]
byteorder = "*"
bv = "*"
ggez-goodies = "*"
failure = "*"
failure_derive = "*"
#image = "*"
rect_packer = "*"
specs = "*"
specs-derive = "*"
serde = "*"
serde_yaml = "*"
warmy = "*"
maplit = "*"
lazy_static = "*"

[dependencies.ggez]
version = "*"
features = ["cargo-resource-root"]

[dev-dependencies]
rustfmt-nightly = "*"
