cargo-features = ["edition"]

[package]
edition = '2018'
name = "openmoonstone"
version = "0.1.0"
authors = ["Joe Tsoi <joetsoi@users.noreply.github.com>"]

[dependencies]
byteorder = "1.2.3"
bv = "0.7.4"
image = "0.19.0"
rect_packer = "0.2.1"
specs = "0.12.0"
specs-derive = "0.2.0"
serde = "1.0.70"
serde_yaml = "0.7.5"
warmy = "0.7.2"

[dependencies.ggez]
version = "0.4.3"
features = ["cargo-resource-root"]

[dev-dependencies]
rustfmt-nightly = "0.8.2"
