[package]
name = "openmoonstone"
version = "0.1.0"
authors = ["Joe Tsoi <joetsoi@users.noreply.github.com>"]

[dependencies]
byteorder = "1.2.3"
bv = "0.7.4"

[dependencies.ggez]
version = "0.4.3"
features = ["cargo-resource-root"]
