[package]
name = "loadable_macro_derive"
version = "0.1.0"
authors = ["Joe Tsoi <joetsoi@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.3"
syn = "0.14.4"
