name: Rust

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      working-directory: rust
    - uses: actions/upload-artifact@v1
      with:
        name: openmoonstone-weekly-debug-build
        path: rust/target/debug/openmoonstone.exe
